// Table of Contents data for the Buddhist library
export const tocData = [
  {
    title: '1. Tam Vô',
    items: [
      { id: 'section-01-01-vo-nga', title: 'Vô Ngã' },
      { id: 'section-01-02-vo-tuong', title: 'Vô Tướng' },
      { id: 'section-01-03-vo-niem', title: 'Vô Niệm' },
      { id: 'section-01-04-tam-vo-dai-nguyen', title: 'Tam Vô Đại Nguyện' },
      { id: 'section-01-05-duyen-xuat-the', title: 'Duyên Xuất Thế' },
      { id: 'section-01-06-thu-phat', title: 'Thủ Phất' },
      { id: 'section-01-07-dieu-lien', title: 'Diệu Liên' },
      { id: 'section-01-08-tam-vo-hang-nhat', title: 'Tam Vô Hằng Nhật' },
      { id: 'section-01-09-bach-ngon', title: 'Bạch Ngôn' },
      { id: 'section-01-10-dai-nhan-duyen', title: 'Đại Nhân Duyên' },
      { id: 'section-01-11-dai-duyen-xuong-toc', title: 'Đại Duyên Xuống Tóc' },
      { id: 'section-01-12-phat-cung-gap-nan', title: 'Phật Cũng Gặp Nạn' },
      { id: 'section-01-13-thuyen-bat-nha', title: 'Thuyền Bát Nhã' },
      { id: 'section-01-14-vo-tu-nga', title: 'Vô Tự Ngã' },
    ],
  },
  {
    title: '3. Tìm Đạo',
    items: [
      { id: 'section-03-01-tim-phat', title: 'Tìm Phật' },
      { id: 'section-03-02-duyen-an-vi-phat', title: 'Duyên An Vị Phật' },
      { id: 'section-03-03-tim-lau-dai', title: 'Tìm Lầu Đài' },
      { id: 'section-03-04-bat-vong-do', title: 'Bất Vọng Độ' },
      { id: 'section-03-05-cau-dao', title: 'Cầu Đạo' },
      { id: 'section-03-06-tim-cau', title: 'Tìm Cầu' },
      { id: 'section-03-07-ga-lang-thang', title: 'Gà Lang Thang' },
    ],
  },
  {
    title: '10. Lời Nhắc Nhở',
    items: [
      { id: 'section-10-01-nho-phat', title: 'Nhớ Phật' },
      { id: 'section-10-02-canh-tinh', title: 'Cảnh Tỉnh' },
      { id: 'section-10-03-tu-tam', title: 'Tu Tâm' },
      { id: 'section-10-04-giac-ngo', title: 'Giác Ngộ' },
      { id: 'section-10-05-hanh-dao', title: 'Hành Đạo' },
      { id: 'section-10-06-niem-phat', title: 'Niệm Phật' },
      { id: 'section-10-07-tu-hanh', title: 'Tu Hành' },
      { id: 'section-10-08-giai-thoat', title: 'Giải Thoát' },
      { id: 'section-10-09-thanh-tinh', title: 'Thanh Tịnh' },
      { id: 'section-10-10-bi-tri', title: 'Bi Trí' },
      { id: 'section-10-11-duc-hanh', title: 'Đức Hạnh' },
      { id: 'section-10-12-minh-tam', title: 'Minh Tâm' },
    ],
  },
  {
    title: '11. Phật Chú',
    items: [
      { id: 'section-11-01-3t', title: '3T' },
      { id: 'section-11-02-dai-bi-chu', title: 'Đại Bi Chú' },
      { id: 'section-11-03-tam-quy-y', title: 'Tam Quy Y' },
      { id: 'section-11-04-luc-tu', title: 'Lục Tự' },
      { id: 'section-11-05-a-di-da', title: 'A Di Đà' },
      { id: 'section-11-06-ban-nha', title: 'Bát Nhã' },
      { id: 'section-11-07-quan-am', title: 'Quan Âm' },
      { id: 'section-11-08-dia-tang', title: 'Địa Tạng' },
      { id: 'section-11-09-van-phat', title: 'Vạn Phật' },
    ],
  },
  {
    title: '12. Khai Đạo',
    items: [
      { id: 'section-12-01-khai-tri', title: 'Khai Trí' },
      { id: 'section-12-02-minh-dao', title: 'Minh Đạo' },
      { id: 'section-12-03-khai-dao', title: 'Khai Đạo' },
      { id: 'section-12-04-giac-ngo', title: 'Giác Ngộ' },
      { id: 'section-12-05-tu-tam', title: 'Tu Tâm' },
      { id: 'section-12-06-hanh-dao', title: 'Hành Đạo' },
      { id: 'section-12-07-thanh-tinh', title: 'Thanh Tịnh' },
      { id: 'section-12-08-giai-thoat', title: 'Giải Thoát' },
      { id: 'section-12-09-bi-tri', title: 'Bi Trí' },
      { id: 'section-12-10-duc-hanh', title: 'Đức Hạnh' },
    ],
  },
  {
    title: '13. Mượn Vật Khai Đạo',
    items: [
      { id: 'section-13-01-hoa-sen', title: 'Hoa Sen' },
      { id: 'section-13-02-cay-bo-de', title: 'Cây Bồ Đề' },
      { id: 'section-13-03-mat-trang', title: 'Mặt Trăng' },
      { id: 'section-13-04-nuoc-trong', title: 'Nước Trong' },
      { id: 'section-13-05-gio-may', title: 'Gió Mây' },
      { id: 'section-13-06-nui-song', title: 'Núi Sông' },
      { id: 'section-13-07-chim-muong', title: 'Chim Muông' },
      { id: 'section-13-08-hoa-thao', title: 'Hoa Thảo' },
      { id: 'section-13-09-anh-sang', title: 'Ánh Sáng' },
      { id: 'section-13-10-tieng-chuong', title: 'Tiếng Chuông' },
    ],
  },
  {
    title: '14. Quy Luật',
    items: [
      { id: 'section-14-01-nhan-qua', title: 'Nhân Quả' },
      { id: 'section-14-02-luan-hoi', title: 'Luân Hồi' },
      { id: 'section-14-03-nghiep-luc', title: 'Nghiệp Lực' },
      { id: 'section-14-04-duyen-khoi', title: 'Duyên Khởi' },
      { id: 'section-14-05-vo-thuong', title: 'Vô Thường' },
    ],
  },
  {
    title: '16. Bổn Lai',
    items: [
      { id: 'section-16-01-ban-tinh', title: 'Bản Tính' },
      { id: 'section-16-02-phat-tinh', title: 'Phật Tính' },
      { id: 'section-16-03-thanh-tinh', title: 'Thanh Tịnh' },
      { id: 'section-16-04-vo-sinh', title: 'Vô Sinh' },
      { id: 'section-16-05-vo-diet', title: 'Vô Diệt' },
      { id: 'section-16-06-khong-tinh', title: 'Không Tính' },
      { id: 'section-16-07-nguyen-lai', title: 'Nguyên Lai' },
    ],
  },
  {
    title: '17. Lời Nguyện',
    items: [
      { id: 'section-17-01-nguyen-luc', title: 'Nguyện Lực' },
      { id: 'section-17-02-phat-nguyen', title: 'Phật Nguyện' },
      { id: 'section-17-03-bo-tat-nguyen', title: 'Bồ Tát Nguyện' },
      { id: 'section-17-04-tu-nguyen', title: 'Tứ Nguyện' },
      { id: 'section-17-05-dai-nguyen', title: 'Đại Nguyện' },
      { id: 'section-17-06-nguyen-sinh', title: 'Nguyện Sinh' },
      { id: 'section-17-07-nguyen-hanh', title: 'Nguyện Hạnh' },
      { id: 'section-17-08-nguyen-tam', title: 'Nguyện Tâm' },
      { id: 'section-17-09-nguyen-dao', title: 'Nguyện Đạo' },
      { id: 'section-17-10-nguyen-phat', title: 'Nguyện Phật' },
      { id: 'section-17-11-nguyen-chung', title: 'Nguyện Chúng' },
    ],
  },
  {
    title: '20. Cảm Niệm',
    items: [
      { id: 'section-20-01-cam-on', title: 'Cảm Ơn' },
      { id: 'section-20-02-biet-on', title: 'Biết Ơn' },
      { id: 'section-20-03-tri-an', title: 'Tri Ân' },
      { id: 'section-20-04-hoi-huong', title: 'Hồi Hướng' },
      { id: 'section-20-05-cong-duc', title: 'Công Đức' },
      { id: 'section-20-06-phuoc-bao', title: 'Phước Báo' },
    ],
  },
];
